version: '2'
networks:
  default:
    driver: bridge
services: 
  mongo:
    image: mongo
    mem_limit: 256m
    ports:
      - "27017:27017"
  kafka:
    image: spotify/kafka
    mem_limit: 1g
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: "localhost"
      ADVERTISED_PORT: "9092"
      CONSUMER_THREADS: "1"
      TOPICS: "star-wars-planet-events"
      ZK_CONNECT: "kafka7zookeeper:2181/root/path"
      GROUP_ID: "b2w-starwars"
      NUM_PARTITIONS: "100"
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"      